### ISSUE TITLE
Faulty installation instructions

### ISSUE THREAD

**Issue by durka** [windmilleng/mish#1]
I tried to install `mish` via `go get` as shown in the readme, but it didn't want to:

```
$ go get -u github.com/windmilleng/mish
package github.com/windmilleng/mish: no Go files in /Users/alex/go/src/github.com/windmilleng/mish
```

**Comment by maiamcc** [comment]
Thanks @durka, we'll check this out. In the meantime, what OS are you running? I'll send you a bin so you can get up and running while we work out the kinks in our install process.

**Comment by dbentley** [comment]
Should be fixed in HEAD.

(You need to go get -u github.com/windmilleng/mish/cmd/mish )

**Comment by durka** [comment]
That new `go get` command works!
