### ISSUE TITLE
Not so great UX if kern.maxfiles is too low

### ISSUE THREAD

**Issue by durka** [windmilleng/mish#2]
On macOS 10.13 apparently some kernel settings need to be adjusted for one of mish's dependencies. The error message with a link to [instructions to fix it](https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits) (which say it only applies to macOS <=10.6, but that's apparently not true anymore) appears in mish's log file, but there's otherwise no output as it fails to start.

mish does start after changing the kernel settings as instructed on that page.

**Comment by maiamcc** [comment]
Good call, fixed in 1e1b7be441bcd42dad8a742a10d2059fd960d770!
